### ISSUE TITLE
Bug in collate_fn.py

### ISSUE THREAD

**Issue by lukewys** [audio-captioning/clotho-dataloader#1]
Dear author,

There seems to be a little bug at line 39 in collate_fn.py, where "nb_t_steps.lower" should be "nb_t_steps.lower()", otherwise it will only config the "nb_t_steps" as "min" mode.

Regards

**Comment by dr-costas** [comment]
Thnx! I will push the correction. I'm closing this issue, but please make another one if you spot something else!
